CREATE TABLE users (
    user_id CHAR(36) NOT NULL PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255) UNIQUE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE users
ADD COLUMN role ENUM('ADMIN', 'PLAYER') DEFAULT 'PLAYER';
